# Generated by Django 3.2.6 on 2021-09-01 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('published_date', models.TextField(max_length=50)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField()),
                ('json_id', models.CharField(blank=True, max_length=100, null=True)),
                ('published_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
