# Generated by Django 3.2.6 on 2021-09-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_year',
        ),
    ]
