# Generated by Django 3.2.6 on 2021-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_remove_book_published_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1)),
            ],
        ),
    ]
